"""add unlock voting models

Revision ID: a49676b87569
Revises: 3f62ee4bebd5
Create Date: 2026-04-10 17:32:00.584324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49676b87569'
down_revision: Union[str, Sequence[str], None] = '3f62ee4bebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlock_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlock_proposals_id'), 'unlock_proposals', ['id'], unique=False)
    op.create_table('unlock_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_household_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['unlock_proposals.id'], ),
    sa.ForeignKeyConstraint(['voter_household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_household_id', name='uq_unlock_vote_one_per_household')
    )
    op.create_index(op.f('ix_unlock_votes_id'), 'unlock_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlock_votes_id'), table_name='unlock_votes')
    op.drop_table('unlock_votes')
    op.drop_index(op.f('ix_unlock_proposals_id'), table_name='unlock_proposals')
    op.drop_table('unlock_proposals')
    # ### end Alembic commands ###
