"""initial schema

Revision ID: ee23857a8e9a
Revises: 0
Create Date: 2026-03-02 13:33:22.279674

Esta migración crea todas las tablas necesarias para el funcionamiento de la aplicación.

Los modelos del esquema son:
- households
- users linked to households
- OTP-based authentication flow (auth_otps
- reservations
- waitlist_entries

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee23857a8e9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_otps_email'), 'auth_otps', ['email'], unique=False)
    op.create_index(op.f('ix_auth_otps_id'), 'auth_otps', ['id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_code'), 'households', ['code'], unique=True)
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(), nullable=True),
    sa.Column('prime_time', sa.Boolean(), nullable=False),
    sa.Column('cooldown_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_at', name='uq_reservations_start_at')
    )
    op.create_index('ix_reservations_household_start', 'reservations', ['household_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', name='uq_users_household_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_index('ix_waitlist_start_created', 'waitlist_entries', ['start_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_start_created', table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_index('ix_reservations_household_start', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_index(op.f('ix_households_code'), table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_auth_otps_id'), table_name='auth_otps')
    op.drop_index(op.f('ix_auth_otps_email'), table_name='auth_otps')
    op.drop_table('auth_otps')
    # ### end Alembic commands ###
